# Generated by Django 4.2.1 on 2023-05-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_alter_user_uloga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predmeti',
            old_name='bodovi',
            new_name='ects',
        ),
        migrations.RenameField(
            model_name='predmeti',
            old_name='sem_Redovni',
            new_name='sem_izv',
        ),
        migrations.RenameField(
            model_name='predmeti',
            old_name='sem_izvanredni',
            new_name='sem_red',
        ),
    ]
