# Generated by Django 4.2.1 on 2023-05-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0003_rename_bodovi_predmeti_ects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prezime',
        ),
    ]
