# Generated by Django 4.2.1 on 2023-06-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0008_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upisi',
            name='status',
            field=models.CharField(choices=[('polozen', 'Položen'), ('pad', 'Izgubio pravo'), ('upisan', 'Upisan')], default='upisan', max_length=10),
        ),
    ]
